/* ═════════════════════════════════════════════════════════════
   ENGLISH

   Traducción incompleta a propósito. Lo que falte sale en español,
   que es el comportamiento que define t(): nada se rompe por una
   clave ausente.

   Para seguir traduciendo basta con añadir pares aquí. No hay que
   tocar ni una línea de lógica.

   Las claves acabadas en .one y .other las elige Intl.PluralRules
   con las reglas del idioma, no un `=== 1` escrito a mano.
   ═════════════════════════════════════════════════════════════ */

TEXTOS.en = {

  /* ── Plurales ──────────────────────────────────────────────── */
  'mas.one':       'more',
  'mas.other':     'more',
  'dia.one':       'day',
  'dosis.one':     'dose given',
  'dosis.other':   'doses given',
  'dia.other':     'days',
  'vez.one':       'time',
  'vez.other':     'times',
  'registro.one':  'entry',
  'registro.other':'entries',
  'hijo.one':      'child',
  'hijo.other':    'children',
  'pipi.one':      'wee',
  'pipi.other':    'wees',
  'caca.one':      'poo',
  'caca.other':    'poos',

  /* ── Entrada ───────────────────────────────────────────────── */
  'login.sub':       'Sign in to keep track of your baby',
  'login.google':    'Continue with Google',
  'login.separador': 'or with your email',
  'login.correo':    'Email address',
  'login.pwd':       'Password',
  'login.entrar':    'Sign in',
  'login.registro':  'Create an account',

  /* ── Pestañas ──────────────────────────────────────────────── */
  'tab.registrar': 'Log',
  'tab.graficas':  'Charts',
  'tab.medicacion':'Meds',
  'tab.comida':    'Food',
  'tab.historial': 'History',

  /* ── Resumen ───────────────────────────────────────────────── */
  'resumen.titulo': '🕐 Last 24 h',
  'resumen.desde':  'Since ',

  /* ── Plan ──────────────────────────────────────────────────── */
  'plan.prueba': 'Free trial: {n} {dias} left.',

  /* ── Ajustes ───────────────────────────────────────────────── */
  'ajustes.idioma': 'Language',

  /* ── Recuperar la contraseña ───────────────────────────────── */
  'login.olvide':    'Forgotten your password?',
  'recup.titulo':    'Choose a new password',
  'recup.sub':       'At least 8 characters',
  'recup.campo':     'New password',
  'recup.guardar':   'Save password',
  'recup.guardando': 'Saving…',
  'recup.falta':     'Type your email above and press again.',
  'recup.enviado':   'If that address has an account, you will get an email in a minute.',
  'recup.corta':     'At least 8 characters.',
  'recup.lista':     '✅ Password changed',

  /* ── Pañales ──────────────────────────────────── */
  'pipi.pocos':     'Few wet nappies: {n} in 24 h.',
  'pipi.esperados': 'At his age at least {m} are expected.',
  'pipi.quehacer':  'If you have not simply forgotten to log one, mention it to your doctor.',
  'pipi.fuente':    'Wet nappy rule: one per day of life up to the fifth, and five or more from then on.',

  /* ── Medicación ────────────────────────────────────────────── */
  'med.titulo':      'Medicines',
  'med.hoy':         'Right now',
  'med.nada':        'No dose is due right now.',
  'med.ahora':       'due now',
  'med.hace':        'overdue by',
  'med.luego':       'later',
  'med.ayer':        'yesterday',
  'med.dada':        'Given it',
  'med.dadaA':       'given at',
  'med.nodada':      'not given',
  'med.saltar':      'Record that it was not given',
  'med.deshacer':    'Undo',
  'med.verla':       'Open',
  'med.posponer':    'Snooze {n} min',
  'med.pospuesta':   'snoozed',
  'med.pospuesto':   '⏾ Still not given. I will remind you in {n} min.',
  'med.tu':          'you',
  'med.pareja':      'your partner',
  'med.historial':   'Dose history',
  'med.en30':        'in 30 days',
  'med.anulada':     'undone',
  'med.hoy.dia':     'Today',
  'med.ayer.dia':    'Yesterday',
  'med.tratamientos':'Treatments',
  'med.sinactivos':  'None under way.',
  'med.terminados':  'Finished treatments',
  'med.anadir':      'Add a medicine',
  'med.terminar':    'Stop now',
  'med.hasta':       'until',
  'med.terminaHoy':  'ends today',
  'med.termino':     'ended on',
  'med.empiezaManana':'starts tomorrow',
  'med.empiezaEl':   'starts on',
  'med.borrar':      'Delete',
  'med.horasBloqueadas':'There are doses logged against these times, so they are not edited here.',
  'med.atajoHecho':  '{n} doses a day, from {h}',
  'med.f.atajosAyuda':'Or spread the doses through the day from the first time:',
  'med.f.horasAyuda':'What counts is the list above: tap a time to remove it, or add any you like by hand.',
  'med.f.hastaAyuda':'Empty = no end date.',
  'med.sinfin':      'no end date',
  'med.cada':        'every',
  'med.aldia':       'a day',
  'med.guardada':    'added',
  'med.cambiarHoras':'change the times',
  'med.vacio.sub':   'No treatment yet',
  'med.vacio.txt':   'Write down what the doctor prescribed and at what times. When one of you marks a dose, the reminder disappears from the other phone.',
  'med.rehacerAviso':'The times of a running treatment are not edited: what you already logged would stop matching. This one ends today and the new one starts tomorrow.',
  'med.f.nombre':    'Medicine',
  'med.f.dosis':     'Dose',
  'med.f.dosisAyuda':'Exactly as the doctor told you. The app never works out doses.',
  'med.f.horas':     'Times of day',
  'med.f.anadirHora':'Add time',
  'med.f.quitar':    'Remove',
  'med.f.sinHoras':  'Add at least one time',
  'med.f.desde':     'Starts',
  'med.f.durante':   'For (days)',
  'med.f.duranteAyuda':'Leave it empty if there is no end date.',
  'med.f.hasta':     'Until',
  'med.f.nota':      'Note (optional)',
  'med.pie':         'Tracking Álex is not a medical device and only reminds you when you open it. For a dose that must not be missed, set your phone alarm too. Always follow your doctor’s instructions.',

  /* ── La primera vez ───────────────────────────── */
  'bienv.titulo':   'Welcome!',
  'bienv.empezar':  'Get started',
  'bienv.1':        'This is where you log {n}’s day, in two taps.',
  'bienv.2':        '<strong>What you log, your partner sees at once</strong>, so nobody has to ask whether the medicine has already been given.',
  'bienv.3':        'The tabs are at the bottom, and a short list of first steps at the top.',
  'pasos.titulo':   'To get going',
  'pasos.cuenta':   '{a} of {b}',
  'pasos.tubebe':   'your baby',
  'pasos.ficha':    '{n}’s details, done',
  'pasos.primero':  'Log the first thing',
  'pasos.pareja':   'Invite your partner',
  'pasos.peso':     'Log a weight and see the percentile',
  'pasos.mas':      'Missing something? <strong>Medicines</strong>, <strong>food</strong> and <strong>pumping</strong> can be switched on whenever you like in ',
  'pasos.ocultar':  'Hide this',
  'pasos.ocultada': 'Done. You can get them back in ⚙️ Settings.',
  'pasos.listo':    '✅ You are all set up',
  'pasos.yaEsta':   '✅ All done already: there are no steps left.',
  'ajustes.primerosPasos': 'First steps',
  'ajustes.verPasos':      'Show the first steps again',

  /* ── Avisos en el móvil ────────────────────────── */
  'push.on':            'Turn notifications on',
  'push.off':           'Stop notifying this phone',
  'push.on.titulo':     'This phone gets the reminders',
  'push.on.txt':        'It will tell you when a dose is due and nobody has marked it. This phone only: your partner turns it on from their own.',
  'push.off.titulo':    'Remind me on my phone',
  'push.off.txt':       'Right now the reminder only shows when you open the app. With this, the phone rings even when it is closed.',
  'push.ios.titulo':    'To make your phone ring',
  'push.ios.txt':       'On iPhone, notifications only work if you add Tracking Álex to the home screen. Tap the share button in Safari and choose <strong>Add to Home Screen</strong>. Then open it from there and come back here.',
  'push.no.titulo':     'No notifications in this browser',
  'push.no.txt':        'This browser does not support notifications. The reminder will still appear when you open the app.',
  'push.denegado.titulo':'Notifications blocked',
  'push.denegado.txt':  'You blocked notifications for this site. They have to be allowed again from the browser settings: it cannot be done from here.',
  'med.pie.push':       'Tracking Álex is not a medical device. Phone reminders can arrive late or not at all: battery saving delays them, and a subscription can expire without warning. For a dose that must not be missed, set your phone alarm too. Always follow your doctor’s instructions.',

  /* ── Fechas ───────────────────────────────────────── */
  'fecha.hoy':  'Today',
  'fecha.ayer': 'Yesterday',

  /* ── Enlaces de correo ─────────────────────────────────────── */
  'enlace.caducado': 'That link is no longer valid: it expired or had already been used. Ask for a new one.',
  'enlace.invalido': 'That link is not valid. Ask for a new one.',

  /* ── Botones generales ─────────────────────────────────────── */
  'btn.salir': 'Sign out',

  /* ── Los módulos ───────────────────────────────────────────── */
  'mod.panales.nombre':    'Nappies',
  'mod.panales.desc':      'Wees and poos: amount, colour and notes',
  'mod.peso.nombre':       'Weight',
  'mod.peso.desc':         'Weigh-ins, WHO percentiles and the g/day trend',
  'mod.extraccion.nombre': 'Expressing milk',
  'mod.extraccion.desc':   'Millilitres per breast',
  'mod.comida.nombre':     'Starting solids',
  'mod.comida.desc':       'Introducing foods from six months',
  'mod.medicacion.nombre': 'Medicines',
  'mod.medicacion.desc':   'Your doctor’s schedule, and a nudge when a dose is due',
  'mod.on':                '✅ {m} switched on',
  'mod.off':               '🚫 {m} hidden (nothing has been deleted)',

  /* ── Pantallas que antes se quedaban en español ───────────── */
  'ajustes.anadirHijo':    'Add another child',
  'ajustes.apoyar':        'Support the app',
  'ajustes.app':           'The app',
  'ajustes.borrarCuenta':  'Delete the account',
  'ajustes.compartir':     'Share the charts',
  'ajustes.datos':         'Your data',
  'ajustes.familia':       'Family',
  'ajustes.hijos':         'Children',
  'ajustes.kofi':          'Buy us a coffee',
  'ajustes.modulos':       'What you track',
  'ajustes.nuevoEnlace':   'Create a link',
  'ajustes.segundoAdulto': 'Second adult',
  'ajustes.titulo':        'Settings',
  'alta.bebe':             'Baby’s name',
  'alta.familia':          'Family name',
  'alta.invitado':         'Been invited?',
  'alta.nacimiento':       'Date of birth',
  'alta.nina':             'Girl',
  'alta.nino':             'Boy',
  'alta.pegaCodigo':       'If your partner already created the family, paste their code here',
  'alta.sexo':             'Sex',
  'alta.sexo.txt':         'It is needed for the weight percentile: the WHO has a different curve for each sex, and the wrong one shifts the result.',
  'alta.sub':              'Only asked once',
  'alta.titulo':           'Let’s get started',
  'alta.unirme':           'Join the family',
  'aria.ajustes':          'Settings',
  'aria.borrar':           'Delete',
  'aria.hijo':             'Switch child',
  'aria.tema':             'Switch theme',
  'btn.atras':             '← Back',
  'btn.cancelar':          'Cancel',
  'btn.cerrar':            'Close',
  'btn.editar':            'Edit',
  'btn.guardar':           'Save',
  'btn.guardar2':          'Save changes',
  'btn.siguiente':         'Next',
  'edit.titulo':           '✏️ Edit entry',
  'graf.ext':              'Milk expressed',
  'graf.panales':          'Wees and poos in 24 h',
  'graf.peso':             'Weight',
  'hist.acc':              'Act.',
  'hist.detalle':          'Detail',
  'hist.fecha':            'Date',
  'hist.tipo':             'Type',
  'hist.todo':             'All',
  'ph.bebe':               'Alex',
  'ph.codigo':             'Invitation code',
  'ph.correo':             'you@email.com',
  'ph.familia':            'The Smiths',
  'ph.notaPipi':          'Odd colour, smell, little specks…',
  'ph.nota':               'Texture, smell, whether it was a struggle…',
  'reg.aspecto':           'Look',
  'reg.caca':              '💩 Poo',
  'reg.caca.aviso':        'Pale or bloody ⚠️: mention it to your doctor.',
  'reg.caca.sub':          'Amount and colour',
  'reg.cambiarHora':       'Change the time',
  'reg.cantidad.f':        'Amount (0 = none · 10 = loads)',
  'reg.cantidad.m':        'Amount (0 = none · 10 = loads)',
  'reg.color':             'Colour',
  'reg.der':               'Right',
  'reg.ext.sub':           'Record which breast and how many ml',
  'reg.ext.tit':           '🍼 Expressing milk',
  'reg.fechaHora':         'Date and time',
  'reg.guardaCaca':        'Save poo',
  'reg.guardaExt':         'Save expressing',
  'reg.guardaPeso':        'Save weight',
  'reg.guardaPipi':        'Save wee',
  'reg.izq':               'Left',
  'reg.leche':             '🍼 Milk',
  'reg.ml':                'Amount (ml)',
  'reg.noTransp':          'Not clear',
  'reg.nota':              'Note (optional)',
  'reg.notaHora':          'Note, or change the time',
  'reg.pecho':             'Breast',
  'reg.peso':              '⚖️ Weight',
  'reg.peso.lbl':          'Weight (grams)',
  'reg.peso.sub':          'In grams',
  'reg.peso.tit':          '⚖️ Baby’s weight',
  'reg.pipi':              '💧 Wee',
  'reg.pipi.sub':          'Amount and look',
  'reg.todoOculto':        'Everything is switched off. You can turn things back on in ⚙️ Settings.',
  'reg.transp':            'Clear',
  'seg.alergia':           'Signs of a severe allergic reaction',
  'seg.alergia.txt':       'Trouble breathing, wheezing, swelling of the lips, tongue or face, repeated vomiting, sudden paleness or floppiness, hives all over the body.',
  'seg.arcada':            'Gagging and choking are not the same thing',
  'seg.rcp':               'An infant CPR course takes a couple of hours and sticks far better than anything written down. This app is a notebook: it does not replace your doctor.',
  'seg.sub':               'Worth reading before you start, not during',
  'seg.titulo':            '🚨 If something goes wrong',
  'tomas.one':             'dose',
  'tomas.other':           'doses',
  'tratamientos.one':      'treatment',
  'tratamientos.other':    'treatments',

  /* ── Registrar, historial, gráficas y el panel de 24 h ────── */
  'auth.corto':         'Enter an email address and a password of at least 8 characters.',
  'auth.creada':        'Account created. Check your email to confirm it, then sign in.',
  'auth.malas':         'Wrong email or password.',
  'auth.yaExiste':      'That email already has an account. Sign in instead of registering.',
  'auth.sinConfirmar':  'Confirm your email before signing in.',
  'auth.sinGoogle':     'Signing in with Google is not set up in Supabase yet.',
  'auth.muchos':        'Too many attempts. Wait a minute.',
  'auth.generico':      'That did not go through.',
  'btn.guardando':      'Saving…',
  'aria.editar':        'Edit',
  'graf.pocoPeso':      '⚠️ <strong>Gaining {g} g a day.</strong> In the first month at least {o} g a day is the usual expectation. With only a few weigh-ins this number jumps around a lot, so check there are enough first; if it stays like this, mention it to your doctor.',
  'graf.tendencia':     'Estimated from {n} weigh-ins over the last {d} days ({g} g a day). It is a plain trend line, not a prediction: with few weigh-ins it changes a lot from one day to the next.',
  'graf.sinTendencia':  'At least two weigh-ins, spaced apart, are needed to estimate a trend.',
  'hist.izq':           '🍼 Left',
  'hist.der':           '🍼 Right',
  'hist.pesoTipo':      '⚖️ Weight',
  'hist.cacaTipo':      '💩 Poo',
  'hist.pipiTipo':      '💧 Wee',
  'hist.transp':        'clear',
  'hist.noTransp':      'not clear',
  'hist.todoOculto':    'Everything is switched off. You can turn things back on in ⚙️ Settings.',
  'hist.vacio':         'No entries yet.',
  'hist.vacioTipo':     'No entries of this kind.',
  'hist.borrarQ':       'Delete the entry from {f}?',
  'hist.borrarQ2':      'Delete this entry?',
  'hist.borrado':       '🗑️ Entry deleted',
  'hist.noBorrado':     '❌ Could not delete: ',
  'reg.sinHijo':        '⚠️ No child is selected.',
  'reg.faltaMlFecha':   '⚠️ Enter the ml and the date.',
  'reg.faltaMl':        '⚠️ Enter the ml.',
  'reg.faltaPesoFecha': '⚠️ Enter the weight (500 g minimum) and the date.',
  'reg.faltaPeso':      '⚠️ Enter the weight (500 g minimum).',
  'reg.faltaCant':      '⚠️ Enter the amount.',
  'reg.faltaCantFecha': '⚠️ Enter the amount and the date.',
  'reg.fechaMala':      '⚠️ That date is not valid.',
  'reg.okExt':          '✅ Expressing saved',
  'reg.okPeso':         '✅ Weight saved',
  'reg.okCaca':         '✅ Poo saved',
  'reg.okPipi':         '✅ Wee saved',
  'reg.okEditado':      '✅ Entry updated',
  'reg.noEditable':     'This kind of entry cannot be edited here.',
  'reg.noGuardado':     '❌ Could not save: ',
  'reg.errorRaro':      'unknown error',
  'reg.sinCambios':     '⚠️ Nothing changed. The UPDATE policy is missing in Supabase (migracion.sql).',
  'sum.pipis':          'Wees',
  'sum.cacas':          'Poos',
  'sum.leche':          'Milk',
  'sum.alimentos':      'Foods',
  'sum.alergenos':      'Allergens',
  'sum.izq':            'L',
  'sum.der':            'R',
  'sum.oms':            'WHO',
  'sum.juntas':         'g/day: weigh-ins too close together',
  'sum.faltan':         'g/day: not enough weigh-ins',
  'sum.mantiene':       'Holding their percentile',
  'sum.primerMes':      'In the first month at least {o} g a day is the usual expectation',
  'sum.pordebajo':      'Below what it would take to stay on the same percentile. Dropping a percentile is not, on its own, a problem',
  'sum.ajuste':         'Fitted over {n} weigh-ins from the last {d} days',
  'sum.pctTit':         'Weight for age (WHO). {d} days old, z = {z}',
  'sum.pctNd':          'percentile n/a',
  'sum.deTotal':        'of {n} · all time',
  'sum.conReaccion':    '{n} with a reaction',
  'sum.sinReaccion':    'no reactions',
  'sum.todoOculto':     'Everything is hidden. You can switch it back on in ⚙️ Settings.',
  'u.gdia':             'g/day',
  'sum.needTit':     'The slope of the WHO curve at their current point: what they would have to gain to stay on the same line. It changes with age — it rises until about three weeks and then falls — and dropping a percentile is not, on its own, a problem.',
  'sum.need':        '{g} g/day to hold {p}',
  'sum.needSin':     '{g} g/day to hold their percentile',
  'sum.ultimoPeso':  'Last weigh-in',
  'sum.sinDatos':    'no data',

  /* ── ⚙️ Ajustes ─────────────────────────────────────────────── */
  'aj.nombre':        'Name',
  'aj.anadir':        'Add',
  'aj.invita':        'Generate a code and pass it on. A family takes two adults at most.',
  'aj.generarCodigo': 'Generate an invitation code',
  'aj.dosAdultos':    'A family can only have two adults.',
  'aj.pasosTxt':      'The short list of things to do when you start.',
  'aj.exportTxt':     'Take it all with you whenever you like, without asking anyone. The JSON is the complete copy; the CSV opens in a spreadsheet.',
  'aj.expJSON':       'Download everything (JSON)',
  'aj.expCSV':        'Entries (CSV)',
  'aj.expMed':        'Medicines (CSV)',
  'aj.borrarTxt':     'Deletes your account and, if you are the only adult in the family, everything in it. It cannot be undone and we cannot recover it either.',
  'aj.borrarBtn':     'Delete my account',
  'aj.cargando':      'Loading…',
  'aj.faltaFamilia':  'Give the family a name.',
  'aj.faltaBebe':     'Give the baby a name.',
  'aj.faltaFecha':    'The date of birth is missing.',
  'aj.nombreVacio':   'The name cannot be left empty.',
  'aj.okNombre':      '✅ Name updated',
  'aj.okHijo':        '✅ Child added',
  'aj.okDatos':       '✅ Details updated',
  'pie.privacidad':   'Privacy',
  'pie.terminos':     'Terms',
  'pie.legal':        'Legal notice',

  /* ── Enlaces compartidos, datos y avisos ──────────────────── */
  'enl.abriendo':      'Opening…',
  'enl.caducado.tit':  'This link has expired',
  'enl.caducado.txt':  'Shared links expire on their own after a while. Ask whoever sent it to you for a new one.',
  'enl.revocado.tit':  'This link is no longer active',
  'enl.revocado.txt':  'Whoever created it has switched it off. If you think that is a mistake, tell them and they will send you a new one.',
  'enl.invalido.tit':  'This link is not valid',
  'enl.invalido.txt':  'It may have been copied only half way: links have to go all the way to the end, including the part after the hash. Try opening it again from the original message.',
  'enl.red.tit':       'Could not connect',
  'enl.red.txt':       'Check your connection and try again.',
  'enl.sinDatos':      'Nothing has been recorded yet.',
  'enl.hasta':         'Data up to {f}',
  'enl.viejo':         ' — nothing has been recorded for {d} days, so what you see here is not up to date.',
  'enl.hace':          ' ({d} days ago).',
  'pie.queEs':         'What Tracking Álex is',
  'leg.pesadas':       'Weigh-ins',
  'leg.tendencia':     'Trend',
  'leg.percentiles':   'WHO percentiles',
  'enl.30dias':        '30 days',
  'enl.6meses':        '6 months',
  'enl.nunca':         'Never expires',
  'enl.caducadoYa':    'Expired',
  'enl.caducaEn':      'Expires in {d} {p}',
  'enl.sinAbrir':      'Not opened yet',
  'enl.vistoHoy':      'Opened today',
  'enl.vistoAyer':     'Opened yesterday',
  'enl.vistoHace':     'Opened {d} days ago',
  'enl.noCargan':      'Could not load them.',
  'enl.ninguno':       'There are no active links right now.',
  'enl.sinNombre':     'Unnamed',
  'enl.ensena':        'Shows:',
  'enl.copiar':        'Copy',
  'enl.desactivar':    'Switch off',
  'enl.desactivando':  'Switching off…',
  'enl.desactivado':   '🔒 Link switched off',
  'enl.noDesactivado': 'Could not switch it off',
  'enl.seguro':        'Sure?',
  'enl.tituloNuevo':   '🔗 Share the charts',
  'enl.paraQuien':     'Who is it for?',
  'enl.phEtiqueta':    'grandma, the midwife…',
  'enl.etiquetaTxt':   'It is only so you know which one to switch off later. Whoever opens the link does not see it.',
  'enl.quePodra':      'What will they see?',
  'enl.cPeso':         '⚖️ Weight and percentiles',
  'enl.cPanales':      '💧 Nappies',
  'enl.cExt':          '🍼 Expressing milk',
  'enl.cResumen':      '🕐 The last 24 hours summary',
  'enl.cuanto':        'For how long?',
  'enl.crear':         'Create the link',
  'enl.creando':       'Creating…',
  'enl.creado':        '✅ Link created',
  'enl.eligeUna':      'Pick at least one chart to share.',
  'enl.noCreado':      'Could not create the link.',
  'enl.copiarEnlace':  'Copy the link',
  'enl.copiado':       '📋 Link copied',
  'enl.copiaManual':   'Copy the link',
  'enl.volverAjustes': 'Back to Settings',
  'enl.q.peso':        'weight',
  'enl.q.panales':     'nappies',
  'enl.q.ext':         'expressing',
  'enl.q.resumen':     '24 h summary',
  'btn.volver':        'Back',
  'dat.palabra':       'DELETE',
  'dat.escribe':       'Type {p} to confirm',
  'dat.escribePunto':  'Type {p} to confirm.',
  'dat.nota':          'Complete export of the family data. Dates are ISO 8601 and in UTC.',
  'dat.noLeidos':      'Could not read the data.',
  'dat.sinMed':        'There is no treatment to export.',
  'dat.noFamilia':     '❌ Could not check the family: ',
  'push.noSoporta':    '⚠️ This browser does not support reminders.',
  'push.bloqueado':    '🔕 You have blocked reminders. You can allow them again in your browser settings.',
  'push.sinPermiso':   '🔕 Without permission I cannot remind you.',
  'push.noPreparado':  '❌ Could not set the reminder up.',
  'push.noSuscrito':   '❌ The browser would not let it subscribe: ',
  'push.noGuardado':   '❌ Could not save: ',
  'push.otroNav':      ' browser: this cannot be done from here.',
  'push.soloEste':     'This phone only: your partner turns it on from their own.',
  'push.conEsto':      'With this, the phone rings even when the app is closed.',

  /* ── Colores, alta, plan y gráficas ───────────────────────── */
  'color.mostaza':     'Mustard yellow',
  'color.amarillo':    'Pale yellow',
  'color.verde':       'Greenish',
  'color.marron':      'Brown',
  'color.naranja':     'Orange',
  'color.negro':       'Black (meconium)',
  'color.blanquecino': 'Pale ⚠️',
  'color.rojizo':      'Reddish / blood ⚠️',
  'alta.queLlevar':    'What do you want to track?',
  'alta.eligeUna':     'Pick at least one. The rest switch on later in Settings.',
  'alta.noModulos':    '⚠️ Could not save what you want to track. You can set it in ⚙️ Settings.',
  'alta.pegaCod':      'Paste the code you were given.',
  'aj.fechaLejos':     'That date is a long way off. Is the year right?',
  'aj.sinPermiso':     'You do not have permission. Has the session expired?',
  'aj.nombreFamilia':  '✏️ Family name',
  'aj.noGuardadoPerm': 'Could not save (no permission).',
  'aj.noCoincide':     'The name does not match.',
  'aj.noBorradoDe':    'Could not delete from ',
  'aj.unicoHijo':      'This is the only child in the family. If you delete them, the app has nothing to show and there is no screen to start again from. To correct a name or a date, edit it above.',
  'aj.noCuenta':       'Could not check how many entries they have. Deleting them would take their whole history with it.',
  'aj.sinRegistros':   'No entries yet.',
  'plan.terminada':    'The trial is over. You can still look at everything and export it, but not add new entries.',
  'graf.panales24':    'nappies in 24 h',
  'graf.sinPanales':   'No nappies recorded yet.',
  'graf.notaPanal':    'Each dot is a nappy, and its height is how many there were in the previous 24 hours, including itself. The first day always climbs from 1 because the window is not full yet: that climb means nothing.',
  'mod.noGuardado':    'Could not save',
  'mod.noGuardado2':   '❌ Could not save: ',
  'comp.noImagen':     '❌ Could not create the image: ',

  /* ── Medicinas y alimentación ─────────────────────────────── */
  'med.muySeguida':      'The last one was {a} ago, and doses should be {b} apart.',
  'med.otraMas':         'Are you sure another one is due?',
  'med.noDadaAviso':     'You are recording that this dose was NOT given.',
  'med.noDadaAviso2':    'The reminder will clear on your partner’s phone too.',
  'med.seguir':          'Carry on?',
  'med.noGuardado':      '❌ Could not save: ',
  'med.noGuardado2':     'Could not save',
  'med.anotadoNo':       '📝 Recorded: the {h} one was not given',
  'med.laMarco':         '{q} marked it {t} ago.',
  'med.dobleDosis':      'If you have just given it as well, there has been a double dose: check between you before giving it again.',
  'med.yaMarcada':       '👌 {q} had already marked it ({f})',
  'med.yaNoDada':        '👌 It was already recorded as not given',
  'med.deshacerQ':       'Undo this dose?\n\nIt stays recorded as cancelled and the reminder comes back.',
  'med.faltaNombre':     '⚠️ Give the medicine a name.',
  'med.faltaHora':       '⚠️ Add at least one time.',
  'med.faltaInicio':     '⚠️ The start date is missing.',
  'med.nombreVacio':     '⚠️ The name cannot be left empty.',
  'med.cierraHoy':       'This one closes today and the new one starts tomorrow.',
  'med.terminarQ':       'Stop {m}?',
  'med.terminarTxt':     'It will stop reminding you, including any doses left today.',
  'med.terminarTxt2':    'What is already recorded is not deleted.',
  'med.terminado':       '🏁 {m} stopped',
  'med.noTerminado':     'Could not stop it',
  'med.borrarQ':         'Delete {m} completely?',
  'med.borrarTomas':     'Its {n} recorded {p} will be deleted too.',
  'med.sinTomas':        'It has no recorded doses.',
  'med.borrarIrrev':     'This cannot be undone. If you only want to stop giving it, use “Stop now”.',
  'med.noBorradasTomas': 'Could not delete the doses',
  'med.rlsPautas':       '⚠️ Nothing changed. Check the UPDATE policy on med_pautas.',
  'med.rlsTomas':        '⚠️ Nothing changed. Check the UPDATE policy on med_tomas.',
  'com.noCargan':        '❌ Could not load the foods: ',
  'com.migracion':       ' — have you run migracion-alimentos.sql?',
  'com.sinColumna':      'the "revisado" column is missing — run migracion-alimentos-2.sql in Supabase',
  'com.sinSesion':       'you are not signed in (or it expired). Sign in again.',
  'com.senal1':          'Sits up with little support',
  'com.senal2':          'Holds their head steady',
  'com.senal3':          'No longer pushes food back out with their tongue',
  'com.senal4':          'Shows interest: looks, grabs, brings things to their mouth',
  'com.aComer':          '🥑 Time to eat!',
  'com.nadaPendiente':   'Nothing left to try at their age. Have a look at the catalogue to repeat something or pick up what you skipped.',
  'com.cuandoEmpiece':   'What to offer will appear here once you start. Press “We have started” above.',
  'com.sentoBien':       'Went down well',
  'com.borrarRegQ':      'Delete this entry?',
  'com.noBorrado':       '❌ Could not delete: ',
  'com.marcaCasilla':    '⚠️ Tick the box to record it anyway.',
  'com.noGuardado':      '❌ Could not save: ',
  'com.registrado':      '✅ Recorded · mark later how it went',
  'com.sinCambios':      '⚠️ Nothing changed. Are you signed in?',
  'com.okReaccion':      '⚠️ Reaction recorded',
  'com.anadirAlimento':  '➕ Add a food',
  'com.ponNombre':       '⚠️ Give it a name.',
  'com.okAlimento':      '✅ Food added',
  'com.borrarAlimQ':     'Delete this food?',
  'com.borrarAlimTxt':   'those entries stay in the diary but will no longer count in the catalogue. Carry on?',
  'com.queTalFue':       'How did it go: ',
  'com.huboReaccion':    'There was a reaction',
  'com.resTitulo':       'STARTING SOLIDS — ',
  'com.resReaccion':     ' — REACTION',
  'com.resAlergenos':    'ALLERGENS',
  'com.sinIntroducir':   'not introduced',
  'com.conReaccion':     'with a reaction',
  'com.copiado':         '📋 Copied to the clipboard',
  'com.resumenPedi':     'Summary for the doctor',
  'aj.tieneRegs':      'They have {n} {p}. Deleting them deletes all of it, and that cannot be undone.',
  'aj.borrarHijoND':   'Could not check how many entries {h} has. Everything of theirs will be deleted. This cannot be undone.',
  'aj.borrarHijoN':    '{n} {p} belonging to {h} will be deleted. This cannot be undone.',
  'aj.borrarHijo0':    '{h} will be deleted. According to the database they have no entries.',
  'com.noEmpezado':     'You have not started yet',
  'com.faltanDias':     '{n} {p} to go until six months',
  'com.yaSeis':         'Already six months old',
  'com.seisMeses':      'Six months is the reference, not an exact date. What matters is that {h} is ready:',
  'com.cuatroSenales':  'With all four signs, they look ready to start.',
  'com.yaEmpezamos':    'We have started',
  'com.pulsaloTxt':     'Press it the first time you offer them food, however many days are left.',
  'com.siguiente':      'Next up',
  'com.ordenTxt':       'A suggested order prioritising iron. It is not an official schedule: the AEP says the order does not matter, so move it around as you like.',
  'com.comoDarlo':      'How to offer it',
  'com.catalogo':       'Catalogue',
  'com.catalogoSub':    '{n} foods{m}. Tap one to see how to offer it.',
  'com.vuestros':       ' ({n} of yours)',
  'com.anadirVuestro':  'Add a food of your own',
  'com.deDonde':        'Where all this comes from',
  'com.referencias':    '{n} references. Every age and every figure on this tab comes from them.',
  'com.nadaRegistrado': 'Nothing recorded yet.',
  'leg.percentilesSexo':   'WHO percentiles ({s})',
  'alta.ninos':            'boys',
  'alta.ninas':            'girls',
  'leg.pipis':     'Wees:',
  'leg.cacas':     'Poos:',
  'leg.ninguna':   'none yet',
  'leg.tamano':    'The size of the dot is the amount',
};
